export const blogData = [
  {
    category: "recommendation",
    id: "/blog/cat",
    image: "image/cat.jpg",
    liked: 11,
    bookmarked: 2,
    commented: 1,
    shared: 1,
  },
  {
    category: "recommendation",
    id: "/blog/elka",
    image: "image/elka.jpg",
    liked: 18,
    bookmarked: 3,
    commented: 2,
    shared: 1,
  },
  {
    category: "recommendation",
    id: "/blog/divan",
    image: "image/divanpokupki.jpeg",
    liked: 35,
    bookmarked: 6,
    commented: 5,
    shared: 8,
  },
  {
    category: "recommendation",
    id: "/blog/kitchenbar",
    image: "image/IMG_7682.JPG",
    liked: 27,
    bookmarked: 5,
    commented: 4,
    shared: 7,
  },
  {
    category: "recommendation",
    id: "/blog/kitchenbar",
    image: "image/IMG_7682.JPG",
    liked: 27,
    bookmarked: 5,
    commented: 4,
    shared: 7,
  },
  {
    category: "recommendation",
    id: "/blog/kitchenbar",
    image: "image/IMG_7682.JPG",
    liked: 27,
    bookmarked: 5,
    commented: 4,
    shared: 7,
  },
];
