export const cardData = [
  {
    category: "starRate",
    img: "image/chris.jpg",
    boldText: "Ёлка дома",
    text: "Посмотрите как приобразилась гостинная с ёлкой, смотрится очень гармонично",
    stars: 3,
  },
  {
    category: "starRate",
    img: "image/christma.jpg",
    boldText: "Зал ты прекрасен!",
    text: "Всё таки зелень украшает квартиру, уже чувствуешь себя как на природе",
    stars: 4,
  },
  {
    category: "starRate",
    img: "image/IMG_7849.jpg",
    boldText: "Зал в village стиле",
    text: "Дизайнерская идея для большого простаранства и больших окон",
    stars: 5,
  },
  {
    category: "starRate",
    img: "image/IMG_7853.jpg",
    boldText: "Угловые окна!",
    text: "Оформление для комнаты на крыше в стиле минимализма",
    stars: 2,
  },
  {
    category: "starRate",
    img: "image/IMG_7850.jpg",
    boldText: "Зал в стиле Гэтсби!",
    text: "Все в стиле 18 века по просьбе заказчика получился просто нереальным",
    stars: 3,
  },
  {
    category: "starRate",
    img: "image/IMG_7855.jpg",
    boldText: "Утро начинается с кофе!",
    text: "Милое и уютное простарнство для нашей кухни",
    stars: 2,
  },
  {
    category: "thumbRate",
    img: "image/reg-one.jpg",
    boldText: "Преображение спальной комнаты!",
    text: "Идея для дизайна спальни в белом цвете",
    likes: "86",
    dislikes: "4",
  },
  {
    category: "thumbRate",
    img: "image/reg-two.jpg",
    boldText: "Ручная работа такая редкость в наше время!",
    text: "Коридор теперь смотрится по новому",
    likes: "124",
    dislikes: "4",
  },
  {
    category: "thumbRate",
    img: "image/reg-three.jpg",
    boldText: "Наконец то купили новый диван",
    text: "Картины с ним очень гармонично смотрятся",
    likes: "564",
    dislikes: "22",
  },
  {
    category: "thumbRate",
    img: "image/reg-four.jpg",
    boldText: "Люблю белый цвет!",
    text: "Очень уютный дом кругом красота",
    likes: "78",
    dislikes: "2",
  },
  {
    category: "thumbRate",
    img: "image/reg-six.jpg",
    boldText: "Спальня моей принцессы!",
    text: "Наконец то оформили детскую комнату",
    likes: "254",
    dislikes: "10",
  },
  {
    category: "thumbRate",
    img: "image/reg-seven.jpg",
    boldText: "Моя уютная спальня",
    text: "Все сшила своими руками",
    likes: "36",
    dislikes: "4",
  },
  {
    category: "thumbRate-slim",
    img: "image/IMG_7706.jpg",
    boldText: "Гостиная для приема гостей",
    text: "Оцените наши новые лампы",
    likes: "1347",
    dislikes: "56",
  },
  {
    category: "thumbRate-slim",
    img: "image/IMG_7707.jpg",
    boldText: "Новая полка!",
    text: "Ничего лишнего не должно быть чтобы не засорять полки",
    likes: "896",
    dislikes: "31",
  },
  {
    category: "thumbRate-slim",
    img: "image/IMG_7709.jpg",
    boldText: "Чайный столик!",
    text: "Как красиво и эстетично смотрится наш новый столик в гостиной",
    likes: "736",
    dislikes: "21",
  },
  {
    category: "thumbRate-slim",
    img: "image/IMG_7710.jpg",
    boldText: "Зона для отдыха",
    text: "так давно мечтали о таком телевизоре",
    likes: "1144",
    dislikes: "47",
  },
  {
    category: "thumbRate-slim",
    img: "image/IMG_7711.jpg",
    boldText: "Пуфик ручной работы",
    text: "Посмотрите как гармонично смотрится ковер и новый пуфик",
    likes: "1074",
    dislikes: "52",
  },
  {
    category: "thumbRate-tall",
    img: "image/reg-eight.jpg",
    boldText: "Тропики в твоем доме!",
    text: "Очень освежает комнату вы только посмотрите сколько листьев",
    likes: "2476",
    dislikes: "61",
  },
  {
    category: "thumbRate-tall",
    img: "image/reg-nine.jpg",
    boldText: "Белый всегда в моде",
    text: "не смогла удержаться и купила опять белый декор",
    likes: "3895",
    dislikes: "97",
  },
  {
    category: "thumbRate-tall",
    img: "image/IMG_7676.jpg",
    boldText: "Модный дизайн гостиной!",
    text: "Как вам сочетание цветов все подбирал наш дизайнер",
    likes: "2761",
    dislikes: "74",
  },
  {
    category: "thumbRate-tall",
    img: "image/IMG_7712.jpg",
    boldText: "Дерево всегда актуально!",
    text: "Оцените как все сочетается и подходит по стилю",
    likes: "3975",
    dislikes: "107",
  },
  {
    category: "price",
    img: "image/IMG_7848.jpg",
    text: "Преобразите свой дом в оазис уюта и элегантности с нашим роскошным белым диваном. Этот изысканный предмет мебели не только станет фокусом вашего интерьера, но также добавит нотку свежести и стиля в вашу жилую зону.",
    discount: "34%",
    price: "299 000 тг",
    reviews: "45",
  },
  {
    category: "price",
    img: "image/reg-eleven.jpg",
    text: "Представляем вам уникальную возможность обогатить свой дом стильным и комфортабельным белым креслом. Это кресло не только привнесет свежесть в ваш интерьер, но и станет идеальным уголком для расслабленного отдыха после напряженного дня.",
    discount: "29%",
    price: "149 990 тг",
    reviews: "12",
  },
  {
    category: "price",
    img: "image/reg-twelve.jpg",
    text: "Компактное и стильное решение для вашей обеденной или гостиной зоны - небольшой круглый стол в комплекте с 4 элегантными стульями. Этот набор не только экономит пространство, но и добавляет уют и шарм вашему дому.",
    discount: "14%",
    price: "244 000 тг",
    reviews: "36",
  },
  {
    category: "price",
    img: "image/regthirteen.jpg",
    text: "Этот набор, включающий в себя стильный овальный стол и 4 ярких разноцветных стула, призван придать вашему интерьеру игривость и оригинальность. Создайте пространство, которое будет радовать глаз и приносить удовольствие в каждом моменте.",
    discount: "48%",
    price: "199 000 тг",
    reviews: "56",
  },
  {
    category: "price",
    img: "image/IMG_7837.jpg",
    text: "Погрузитесь в мир роскоши и стиля с нашим уникальным предложением – элегантным зеркалом и раковиной необычной формы. Этот комплект придаст вашей ванной комнате художественный шик и индивидуальность.",
    discount: "35%",
    price: "288 000 тг",
    reviews: "7",
  },
  {
    category: "price",
    img: "image/odeyalopokupki.jpeg",
    text: "Мягкий антибактериальный набор одеял Castella из кукурузного хлопка, межсезонный/всесезонный комплект одеяла",
    discount: "26%",
    price: "99 990 тг",
    reviews: "33",
  },
  {
    category: "price",
    img: "image/divan2pokupki.jpeg",
    text: "Великолепный белый кожаный диван - воплощение роскоши и стиля. Этот диван не только придаст вашему интерьеру изысканность, но и обеспечит максимальный уровень комфорта для ваших моментов отдыха.",
    discount: "17%",
    price: "499 990 тг",
    reviews: "25",
  },
  {
    category: "price",
    img: "image/divanpokupki.jpeg",
    text: "Уютное решение для вашего пространства - мягкий угловой диван в нежном бежевом оттенке. Этот диван не только создаст уют в вашем доме, но и станет стильным акцентом в вашем интерьере.",
    discount: "34%",
    price: "333 990 тг",
    reviews: "45",
  },
  {
    category: "price-popular",
    img: "image/reg-fourteen.jpg",
    text: "Эта картина станет великолепным дополнением к вашему интерьеру, создавая точку фокуса и принося неповторимое искусство в ваш дом. Позвольте себе наслаждаться красотой искусства каждый день.",
    discount: "23%",
    price: "34 990 тг",
    reviews: "15",
  },
  {
    category: "price-popular",
    img: "image/IMG_7714.jpg",
    text: "Погрузитесь в мир изысканности с нашей впечатляющей вазой необычной формы. Эта ваза не только станет великолепным элементом декора, но и придаст вашему интерьеру артистичность и художественную выразительность.",
    discount: "18%",
    price: "26 990 тг",
    reviews: "24",
  },
  {
    category: "price-popular",
    img: "image/IMG_7678.jpg",
    text: "идеальный комплект для вашей обеденной комнаты - круглый стол и 4 серых стула. Этот набор сочетает в себе функциональность, элегантность и современный стиль, создавая уютное пространство для семейных обедов и встреч с друзьями.",
    discount: "44%",
    price: "199 000 тг",
    reviews: "39",
  },
  {
    category: "price-popular",
    img: "image/IMG_7687.jpg",
    text: "Представляем вашему вниманию уникальный серый угловой диван, который станет неотъемлемым элементом современного интерьера. Этот диван сочетает в себе элегантный дизайн и высокий уровень комфорта, предоставляя вам и вашим гостям место для отдыха с изыском.",
    discount: "35%",
    price: "277 000 тг",
    reviews: "12",
  },
  {
    category: "thumbViews",
    img: "image/elka.jpg",
    text: "Создаем новогоднее настроение",
    likes: "524",
    views: "1762",
  },
  {
    category: "thumbViews",
    img: "image/IMG_8387.jpg",
    text: "Зона для отдыха нового формата",
    likes: "216",
    views: "988",
  },
  {
    category: "thumbViews",
    img: "image/IMG_8388.jpg",
    text: "Зеркало необычной формы как основная идея дизайна",
    likes: "42",
    views: "567",
  },
  {
    category: "thumbViews",
    img: "image/IMG_8389.jpg",
    text: "Идея дизайна с тумбочкой и креслом",
    likes: "142",
    views: "890",
  },
  {
    category: "thumbViews",
    img: "image/IMG_8386.jpg",
    text: "Принимаем гостей в удобной гостиной",
    likes: "613",
    views: "1392",
  },
  {
    category: "thumbViews",
    img: "image/IMG_8390.jpg",
    text: "Дeревянный аксессуары для кухни",
    likes: "71",
    views: "485",
  },
  {
    category: "thumbViews",
    img: "image/IMG_7842.jpg",
    text: "Тренд этого сезона кривые зеркала",
    likes: "245",
    views: "973",
  },
  {
    category: "thumbViews",
    img: "image/IMG_8392.jpg",
    text: "Атмосфера Нового года в большом зале",
    likes: "641",
    views: "1502",
  },
];